name: salamandra
version: '0.3'
summary: Gwap implementation over NodeJS http://liberiot.org/
description: |
  Salamandra is a local implementation of Liberiot. It acts as any other Liberiot gateway (packet forwarder), transmitting raw GWAP packets to the liberiot cloud and also converting GWAP packets to MQTT locally. This means that Salamandra can be used to pass MQTT packets to a local automation server, enabling local programmings. Salamandra is then specially indicated for home and building automation.

grade: stable 
confinement: strict 

apps:
  salamandra:
    command: bin/salamandra $1
    daemon: simple
    plugs: [network-bind]

parts:
  webserver:
    source: .
    plugin: nodejs